### ISSUE TITLE
when to gc an image?

### ISSUE THREAD

**Issue by allencloud** [rancher/sherdock#57]
Hi, 
This is an awesome project, indeed.
And when I read the Readme.md and read code of this project, I still can not understand the gc of docker images. 
Can someone explain some for me ?

**Comment by ankushagarwal** [comment]
It's a very simple algorithm right now. It runs an infinite loop, sleeping every `GCIntervalMinutes`. In each loop, it checks for images which matches the provided list of regexes and `saves` them. It also `saves` the images which you configure to `pull` frequently. It deletes all the other images and their intermediate layers. Here is the code : https://github.com/rancherio/sherdock/blob/master/images/gc.go#L82
